name: Symfony

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install PHPMD
      run: composer global require phpmd/phpmd
    - name: Install PHPCS
      run: composer global require squizlabs/php_codesniffer
    - name: Run Code Review with phpcs
      run: ~/.composer/vendor/bin/phpcs --ignore=vendor ./
    - name: Run Code Review with phpmd
      run: ~/.composer/vendor/bin/phpmd Controller,DependencyInjection,Dto,Entity,Lib,Mapper,Model,Repository,Service,AfrikpaysasSymfonyThirdpartyAdapterBundle.php text cleancode,codesize,design,unusedcode,naming,controversial
